### PR TITLE
made ui changes

### PR DESCRIPTION
**Pull request by GAGANRAGHAV**
# Description

made ui changes.
1. background changed
2. cards hover
3. navbar button 
4. hover

Fixes # 27

## Type of change

ui/ux
 
screenshot---

before--
image

after--
image

https://www.loom.com/share/bb290e57bb5042ea9b9d5a07a84fd44b

# Checklist:

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes
- [x ] Any dependent changes have been merged and published in downstream modules

## Summary by CodeRabbit

- **Style Updates**
	- Enhanced `StyledCard` component with new background color, shadow, and margin adjustments for a refreshed look.
	- Removed the shadow effect from `StyledButton` on hover for a cleaner design.
	- Implemented new `Roboto` font for improved text readability across various components.
	- Updated `Home` component with additional button elements and refined styling for better user interaction.
	- Revamped global background styles with updated gradients and solid color for a modern aesthetic.

### CODE REVIEW

**Comment by ank1traj** [comment]
Please remove the` package-lock.json` file

**Comment by GAGANRAGHAV** [comment]
removed the packagelock.json file from commits

**Comment by ank1traj** [comment]
Please have a look on the review comments too.

**Comment by GAGANRAGHAV** [comment]
please explain can't understand ...a lot said by the bot

**Comment by ank1traj** [comment]
Remove extra spaces and blank line.

**Comment by GAGANRAGHAV** [comment]
done sir

**Comment by ank1traj** [comment]
Nice work, just want to know one thing. Can't we remove the overflow?

**Comment by GAGANRAGHAV** [comment]
Yes sir we can , but can you please be specific what kind of overflow have you encountered

**Comment by ank1traj** [comment]
> Yes sir we can , but can you please be specific what kind of overflow have you encountered

@GAGANRAGHAV Overflow in y-axis

**Comment by GAGANRAGHAV** [comment]
sir are you saying to make the full webpage visible without scrol ?

**Comment by GAGANRAGHAV** [comment]
sir i have made some changes please check.

**Comment by ank1traj** [comment]
Nice work. Still need improvements in UI/UX but it was good work. Thanks for contributing.

**Comment by ank1traj** [comment]
Reverting this PR @GAGANRAGHAV as UI/UX is not looking good in mac. Please work on it.

image

**Comment by GAGANRAGHAV** [comment]
Sir please suggest some as i don't have mac .

**Pull request merged**
